In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.Categorical([1,2,3,1,2,3])


[1, 2, 3, 1, 2, 3]
Categories (3, int64): [1, 2, 3]

In [3]:
pd.Categorical(['a','b','c','a','b','c'])

[a, b, c, a, b, c]
Categories (3, object): [a, b, c]

In [4]:
c = pd.Categorical(['a','b','c','a','b','c'],ordered=True,categories=['c','b','a'])

In [5]:
c

[a, b, c, a, b, c]
Categories (3, object): [c < b < a]

In [6]:
c.min()

'c'

In [7]:
s = pd.Series(["a", "b", "c", "a"],dtype="category")

In [8]:
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a, b, c]

In [9]:
df = pd.DataFrame({"A": ["a", "b", "c", "a"]})
df["B"] = df["A"].astype('category')

In [10]:
df

A  B
0  a  a
1  b  b
2  c  c
3  a  a

In [11]:
 s = pd.Series(np.array([2, 4, 6, 8, 10]),
...               index=['a', 'b', 'c', 'd', 'e'])

In [12]:
s

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [13]:
pd.cut(np.array([1, 7, 5, 4, 6, 3]),3)

[(0.994, 3.0], (5.0, 7.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (0.994, 3.0]]
Categories (3, interval[float64]): [(0.994, 3.0] < (3.0, 5.0] < (5.0, 7.0]]

In [14]:
pd.cut(np.array([1, 7, 5, 4, 6, 3]),3,retbins=True)

([(0.994, 3.0], (5.0, 7.0], (3.0, 5.0], (3.0, 5.0], (5.0, 7.0], (0.994, 3.0]]
 Categories (3, interval[float64]): [(0.994, 3.0] < (3.0, 5.0] < (5.0, 7.0]],
 array([0.994, 3.   , 5.   , 7.   ]))

In [15]:
pd.cut(np.array([1, 7, 5, 4, 6, 3]),3,labels=["bad","medium","good"])

[bad, good, medium, medium, good, bad]
Categories (3, object): [bad < medium < good]

In [16]:
pd.cut([0,1,1,2],bins=4)

[(-0.002, 0.5], (0.5, 1.0], (0.5, 1.0], (1.5, 2.0]]
Categories (4, interval[float64]): [(-0.002, 0.5] < (0.5, 1.0] < (1.0, 1.5] < (1.5, 2.0]]

In [17]:
s = pd.Series(np.array([2, 4, 6, 8, 10]),
...               index=['a', 'b', 'c', 'd', 'e'])

In [18]:
pd.cut(s,3)

a    (1.992, 4.667]
b    (1.992, 4.667]
c    (4.667, 7.333]
d     (7.333, 10.0]
e     (7.333, 10.0]
dtype: category
Categories (3, interval[float64]): [(1.992, 4.667] < (4.667, 7.333] < (7.333, 10.0]]

In [19]:
df = pd.DataFrame({'value':np.random.randint(0,100,20)})

In [20]:
labels = ["{0} - {1}".format(i,i+9) for i in range(0,100,10)]

In [21]:
pd.cut(df.value,range(0,105,10),labels=labels)

0     80 - 89
1     30 - 39
2     40 - 49
3     70 - 79
4       0 - 9
5     30 - 39
6     10 - 19
7     90 - 99
8       0 - 9
9     50 - 59
10    10 - 19
11    60 - 69
12    10 - 19
13      0 - 9
14    80 - 89
15    70 - 79
16    80 - 89
17        NaN
18      0 - 9
19    50 - 59
Name: value, dtype: category
Categories (10, object): [0 - 9 < 10 - 19 < 20 - 29 < 30 - 39 ... 60 - 69 < 70 - 79 < 80 - 89 < 90 - 99]

In [22]:
for val in range(0,101,10):
    print(val)

0
10
20
30
40
50
60
70
80
90
100


In [23]:
df = pd.DataFrame({'value':np.random.randint(0,100,20)})
labels = ["{0} - {1}".format(i,i+9) for i in range(0,100,10)]

In [24]:
df['group'] = pd.cut(df.value,range(0,101,10),right=False,labels=labels) #in this example we are taking values which are random and are in a particular range

In [25]:
df['group']

0     70 - 79
1     90 - 99
2     90 - 99
3     70 - 79
4     70 - 79
5     30 - 39
6     10 - 19
7     90 - 99
8     80 - 89
9     70 - 79
10    90 - 99
11      0 - 9
12    10 - 19
13    20 - 29
14    10 - 19
15    30 - 39
16      0 - 9
17    20 - 29
18    50 - 59
19    90 - 99
Name: group, dtype: category
Categories (10, object): [0 - 9 < 10 - 19 < 20 - 29 < 30 - 39 ... 60 - 69 < 70 - 79 < 80 - 89 < 90 - 99]

In [26]:
labels

['0 - 9',
 '10 - 19',
 '20 - 29',
 '30 - 39',
 '40 - 49',
 '50 - 59',
 '60 - 69',
 '70 - 79',
 '80 - 89',
 '90 - 99']

In [27]:
raw_cat = pd.Categorical(["a", "b", "c", "a"], categories=["b", "c", "d"],
   ....:                          ordered=False)
   ....: 

In [28]:
s = pd.Series(raw_cat)

In [29]:
s

0    NaN
1      b
2      c
3    NaN
dtype: category
Categories (3, object): [b, c, d]

In [30]:
df = pd.DataFrame({"A": ["a", "b", "c", "a"]})

In [31]:
df['B'] = raw_cat

In [32]:
raw_cat = pd.Categorical(["a","b","c","a"],categories=["b","c","d"],ordered=False)

In [33]:
s = pd.Series(raw_cat)

In [34]:
s

0    NaN
1      b
2      c
3    NaN
dtype: category
Categories (3, object): [b, c, d]

In [35]:
df = pd.DataFrame({"A":["a","b","c","a"]})

In [36]:
df["B"] = raw_cat

In [37]:
df

A    B
0  a  NaN
1  b    b
2  c    c
3  a  NaN

In [38]:
df.dtypes

A      object
B    category
dtype: object

In [39]:
df = pd.DataFrame({'A':list('abca'),'B':list('bccd')},dtype="category")

In [40]:
df.dtypes

A    category
B    category
dtype: object

In [41]:
df

A  B
0  a  b
1  b  c
2  c  c
3  a  d

In [42]:
df['A']

0    a
1    b
2    c
3    a
Name: A, dtype: category
Categories (3, object): [a, b, c]

In [43]:
df['B']

0    b
1    c
2    c
3    d
Name: B, dtype: category
Categories (3, object): [b, c, d]

In [44]:
df = pd.DataFrame({'A': list('abca'), 'B': list('bccd')})
df_cat = df.astype('category')
    

In [45]:
df_cat.dtypes

A    category
B    category
dtype: object

In [46]:
from pandas.api.types import CategoricalDtype

In [47]:
s = pd.Series(["a","b","c","a"])
cat_type = CategoricalDtype(categories=["b","c","d"],ordered=True)

In [48]:
s_cat = s.astype(cat_type)

In [49]:
s_cat

0    NaN
1      b
2      c
3    NaN
dtype: category
Categories (3, object): [b < c < d]

In [50]:
spitter = np.random.choice([0,1],5,p=[0.5,0.5])

In [51]:
spitter

array([0, 0, 1, 0, 0])

In [52]:
spitter = np.random.choice([0,1],5,p=[0.5,0.5])
s = pd.Series(pd.Categorical.from_codes(spitter,categories=["train","test"]))

In [53]:
spitter = np.random.choice([0,1],5,p=[0.5,0.5])
s = pd.Series(pd.Categorical.from_codes(spitter,categories=["train","test"]))
s

0    train
1     test
2     test
3     test
4    train
dtype: category
Categories (2, object): [train, test]

In [54]:
s = pd.Series(["a","b","c","a"])
s2 = s.astype('category')

In [55]:
s2.astype(str)

0    a
1    b
2    c
3    a
dtype: object

In [56]:
np.asarray(s2)

array(['a', 'b', 'c', 'a'], dtype=object)

categories:a sequence of unique values and no missing values
ordered: a boolean

In [57]:
from pandas.api.types import CategoricalDtype

In [58]:
CategoricalDtype(['a','b','c'])

CategoricalDtype(categories=['a', 'b', 'c'], ordered=None)

In [59]:
CategoricalDtype(['c','a','b'],ordered=True)

CategoricalDtype(categories=['c', 'a', 'b'], ordered=True)

In [60]:
CategoricalDtype()

CategoricalDtype(categories=None, ordered=None)

In [61]:
c1 = CategoricalDtype(['a','b','c'],ordered=False)
c1 == CategoricalDtype(['a','b','c'],ordered=False)

True

In [62]:
c1 == CategoricalDtype(['a','b','c'],ordered=True)

False

In [63]:
c1 == 'category'

True

In [64]:
cat = pd.Categorical(["a","c","c",np.nan],categories=["b","a","c"])


In [66]:
df = pd.DataFrame({"cat":cat,"s":["a","c","c",np.nan]})

In [67]:
df

cat    s
0    a    a
1    c    c
2    c    c
3  NaN  NaN

In [69]:
df.describe()

cat  s
count    3  3
unique   2  2
top      c  c
freq     2  2

In [71]:
df["cat"].describe()

count     3
unique    2
top       c
freq      2
Name: cat, dtype: object

In [72]:
df["s"].describe()

count     3
unique    2
top       c
freq      2
Name: s, dtype: object

categorical data has categories and ordered property,which list their possible values and whether the ordering matters or not.
s.cat.categories
s.cat.ordered

In [73]:
s = pd.Series(["a", "b", "c", "a"], dtype="category")

In [74]:
s.cat.categories

Index(['a', 'b', 'c'], dtype='object')

In [75]:
s.cat.ordered

False

In [77]:
s = pd.Series(pd.Categorical(["a","b","c","a"],categories=["c","b","a"]))

In [78]:
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [c, b, a]

In [103]:
s = pd.Series(list('babc')).astype(CategoricalDtype(list('abcd')))

In [104]:
s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [105]:
s.unique

<bound method Series.unique of 0    b
1    a
2    b
3    c
dtype: category
Categories (4, object): [a, b, c, d]>

In [106]:
s

0    b
1    a
2    b
3    c
dtype: category
Categories (4, object): [a, b, c, d]

In [107]:
s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [108]:
s.unique()

[b, a, c]
Categories (3, object): [b, a, c]

In [109]:
s = pd.Series(["a", "b", "c", "a"], dtype="category")

In [110]:
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a, b, c]

In [111]:
s.cat.categories = ["Group %s" %g for g in s.cat.categories]

In [112]:
s.cat.categories = ["Group %s" %g for g in s.cat.categories]

In [113]:
s.cat.categories

Index(['Group Group a', 'Group Group b', 'Group Group c'], dtype='object')

In [122]:
s = s.cat.rename_categories([1,2,3])

In [123]:
s = s.cat.rename_categories({1:'x',2:'y',3:'z'})

In [124]:
s

0    x
1    y
2    z
3    x
dtype: category
Categories (3, object): [x, y, z]

In [127]:
s = s.cat.add_categories([4])

ValueError: new categories must not include old categories: {4}

In [128]:
s

0    x
1    y
2    z
3    x
dtype: category
Categories (4, object): [x, y, z, 4]

In [129]:
s = s.cat.remove_categories([4])

In [130]:
s

0    x
1    y
2    z
3    x
dtype: category
Categories (3, object): [x, y, z]

In [131]:
s = pd.Series(pd.Categorical(["a", "b", "a"],
   ....:               categories=["a", "b", "c", "d"]))
   ....: 

In [132]:
s

0    a
1    b
2    a
dtype: category
Categories (4, object): [a, b, c, d]

In [133]:
s.cat.remove_unused_categories()

0    a
1    b
2    a
dtype: category
Categories (2, object): [a, b]

In [134]:
 s = pd.Series(["one", "two", "four", "-"], dtype="category")

In [135]:
s

0     one
1     two
2    four
3       -
dtype: category
Categories (4, object): [-, four, one, two]

In [136]:
s = s.cat.set_categories(['one','two','three','four'])

In [137]:
s

0     one
1     two
2    four
3     NaN
dtype: category
Categories (4, object): [one, two, three, four]

In [138]:
 s = pd.Series(pd.Categorical(["a", "b", "c", "a"], ordered=False))


In [139]:
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a, b, c]

In [140]:
s.sort_values(inplace=True)

In [141]:
s

0    a
3    a
1    b
2    c
dtype: category
Categories (3, object): [a, b, c]

In [142]:
s = pd.Series(["a","b","c","a"]).astype(CategoricalDtype(ordered=True))

In [143]:
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a < b < c]

In [144]:
s.min()

'a'

In [145]:
s.max()

'c'

In [148]:
s = s.cat.as_ordered()

In [149]:
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a < b < c]

In [150]:
s.cat.as_unordered()

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a, b, c]

In [151]:
s = pd.Series([1, 2, 3, 1], dtype="category")

In [152]:
s

0    1
1    2
2    3
3    1
dtype: category
Categories (3, int64): [1, 2, 3]

In [153]:
s = s.cat.set_categories([2,3,1],ordered=True)

In [154]:
s

0    1
1    2
2    3
3    1
dtype: category
Categories (3, int64): [2 < 3 < 1]

In [157]:
s.sort_values(inplace=True) #sorting values according to the categorical order

In [158]:
s

1    2
2    3
0    1
3    1
dtype: category
Categories (3, int64): [2 < 3 < 1]

In [159]:
s.min()

2

In [160]:
s.max()

1

In [161]:
s = pd.Series([1, 2, 3, 1], dtype="category")

In [162]:
 dfs = pd.DataFrame({'A': pd.Categorical(list('bbeebbaa'),
   .....:                                         categories=['e', 'a', 'b'],
   .....:                                         ordered=True),
   .....:                     'B': [1, 2, 1, 2, 2, 1, 2, 1]})
   .....: 

In [165]:
dfs.dtypes

A    category
B       int64
dtype: object

In [166]:
dfs.sort_values(by=['A','B'])

A  B
2  e  1
3  e  2
7  a  1
6  a  2
0  b  1
5  b  1
1  b  2
4  b  2

In [167]:
dfs['A']

0    b
1    b
2    e
3    e
4    b
5    b
6    a
7    a
Name: A, dtype: category
Categories (3, object): [e < a < b]

In [170]:
dfs['A'] = dfs['A'].cat.set_categories(['a','b','e']) #when set categories is used the first element is the least element

In [171]:
dfs['A']

0    b
1    b
2    e
3    e
4    b
5    b
6    a
7    a
Name: A, dtype: category
Categories (3, object): [a < b < e]

In [172]:
dfs.sort_values(by=['A','B'])

A  B
7  a  1
6  a  2
0  b  1
5  b  1
1  b  2
4  b  2
2  e  1
3  e  2

In [180]:
cat = pd.Series([1,2,3]).astype(CategoricalDtype([3,2,1],ordered=True)) # 3 < 2 < 1

In [181]:
cat_base = pd.Series([2,2,2]).astype(CategoricalDtype([3,2,1],ordered=True))

In [182]:
cat_base2 = pd.Series([2,2,2]).astype(CategoricalDtype(ordered=True))

In [177]:
cat

0    1
1    2
2    3
dtype: category
Categories (3, int64): [3 < 2 < 1]

In [178]:
cat_base

0    2
1    2
2    2
dtype: category
Categories (3, int64): [3 < 2 < 1]

In [179]:
cat_base2

0    2
1    2
2    2
dtype: category
Categories (1, int64): [2]

In [183]:
cat > cat_base

0     True
1    False
2    False
dtype: bool

In [184]:
cat > 2

0     True
1    False
2    False
dtype: bool

In [185]:
cat == cat_base

0    False
1     True
2    False
dtype: bool

In [186]:
cat == np.array([1,2,3])

0    True
1    True
2    True
dtype: bool

In [187]:
cat == 2

0    False
1     True
2    False
dtype: bool

In [188]:
base = np.array([1,2,3])

In [189]:
np.asarray(cat) > base

array([False, False, False])

In [190]:
c1 = pd.Categorical(['a','b'],categories = ['a','b'],ordered = False)
c2 = pd.Categorical(['a','b'],categories=['b','a'],ordered=False)

In [191]:
c1 == c2

array([ True,  True])

In [192]:
s = pd.Series(pd.Categorical(["a", "b", "c", "c"],
   .....:               categories=["c", "a", "b", "d"]))
   .....: 
        

In [193]:
s.value_counts()

c    2
b    1
a    1
d    0
dtype: int64

In [194]:
s

0    a
1    b
2    c
3    c
dtype: category
Categories (4, object): [c, a, b, d]

In [196]:
cats = pd.Categorical(['a','b','b','b','c','c','c'],categories=['a','b','c','d'])

In [197]:
cats

[a, b, b, b, c, c, c]
Categories (4, object): [a, b, c, d]

In [198]:
df = pd.DataFrame({"cats":cats,"values":[1,2,2,2,3,4,5]})

In [199]:
df

cats  values
0    a       1
1    b       2
2    b       2
3    b       2
4    c       3
5    c       4
6    c       5

In [200]:
df.groupby("cats")

In [201]:
for val1,val2 in df.groupby("cats"):
    print(val1)
    print(val2)

a
  cats  values
0    a       1
b
  cats  values
1    b       2
2    b       2
3    b       2
c
  cats  values
4    c       3
5    c       4
6    c       5
d
Empty DataFrame
Columns: [cats, values]
Index: []


In [202]:
df.groupby("cats").mean()

values
cats        
a        1.0
b        2.0
c        4.0
d        NaN

In [203]:
cats2 = pd.Categorical(['a','a','b','b'],categories=['a','b','c'])

In [204]:
cats2

[a, a, b, b]
Categories (3, object): [a, b, c]

In [205]:
df2 = pd.DataFrame({"cats":cats2,"B":['c','d','c','d'],"values":[1,2,3,4]})

In [206]:
df2

cats  B  values
0    a  c       1
1    a  d       2
2    b  c       3
3    b  d       4

In [207]:
df2.groupby(["cats","B"]).mean()

values
cats B        
a    c     1.0
     d     2.0
b    c     3.0
     d     4.0
c    c     NaN
     d     NaN

In [209]:
idx = pd.Index(["h", "i", "j", "k", "l", "m", "n"])

cats = pd.Series(["a", "b", "b", "b", "c", "c", "c"],dtype="category", index=idx)
    

values = [1, 2, 2, 2, 3, 4, 5]

df = pd.DataFrame({"cats": cats, "values": values}, index=idx)

In [210]:
df

cats  values
h    a       1
i    b       2
j    b       2
k    b       2
l    c       3
m    c       4
n    c       5

In [211]:
df.iloc[2:4,:]

cats  values
j    b       2
k    b       2

In [212]:
df.iloc[2:4,:].dtypes

cats      category
values       int64
dtype: object

In [213]:
df.loc["h":"j","cats"]

h    a
i    b
j    b
Name: cats, dtype: category
Categories (3, object): [a, b, c]

In [214]:
df.loc["h":"j","cats"].dtypes

CategoricalDtype(categories=['a', 'b', 'c'], ordered=False)

In [215]:
df[df["cats"] == "b"]

cats  values
i    b       2
j    b       2
k    b       2

In [216]:
df.loc["h",:]

cats      a
values    1
Name: h, dtype: object

In [219]:
idx = pd.Index(["h", "i", "j", "k", "l", "m", "n"])

In [168]: cats = pd.Categorical(["a", "a", "a", "a", "a", "a", "a"],
                          categories=["a", "b"])
    

In [169]: values = [1, 1, 1, 1, 1, 1, 1]

In [170]: df = pd.DataFrame({"cats": cats, "values": values}, index=idx)

In [220]:
df

cats  values
h    a       1
i    b       2
j    b       2
k    b       2
l    c       3
m    c       4
n    c       5

In [221]:
df.iloc[2:4,:] = [["a",5],["c",2]]

In [222]:
df

cats  values
h    a       1
i    b       2
j    a       5
k    c       2
l    c       3
m    c       4
n    c       5

In [223]:
df.loc["j":"k","cats"] = pd.Categorical(["a", "a"], categories=["a", "b"])

ValueError: Cannot set a Categorical with another, without identical categories

In [224]:
df = pd.DataFrame({"a": [1, 1, 1, 1, 1], "b": ["a", "a", "a", "a", "a"]})

In [228]:
df.loc[1:2,"a"] = 'b'

In [229]:
df

a  b
0  1  a
1  b  a
2  b  a
3  1  a
4  1  a

In [231]:
df.loc[2:3,"b"] = "B"

In [232]:
df

a  b
0  1  a
1  b  a
2  b  B
3  1  B
4  1  a

In [233]:
import io

In [234]:
s = pd.Series(pd.Categorical(['a', 'b', 'b', 'a', 'a', 'd']))

In [236]:
s.cat.categories = ["very good","good","bad"]

In [237]:
s

0    very good
1         good
2         good
3    very good
4    very good
5          bad
dtype: category
Categories (3, object): [very good, good, bad]

In [238]:
s.cat.set_categories(['very bad','bad','medium','good','very good'])

0    very good
1         good
2         good
3    very good
4    very good
5          bad
dtype: category
Categories (5, object): [very bad, bad, medium, good, very good]

In [239]:
df = pd.DataFrame({'cats':s,"vals":[1,2,3,4,5,6]})

In [240]:
df

cats  vals
0  very good     1
1       good     2
2       good     3
3  very good     4
4  very good     5
5        bad     6

In [241]:
csv = io.StringIO()

In [242]:
csv

In [244]:
df.to_csv(csv)

In [245]:
df

cats  vals
0  very good     1
1       good     2
2       good     3
3  very good     4
4  very good     5
5        bad     6

In [247]:
df2 = pd.read_csv(io.StringIO(csv.getvalue()))

In [248]:
df2

Unnamed: 0       cats  vals
0           0  very good     1
1           1       good     2
2           2       good     3
3           3  very good     4
4           4  very good     5
5           5        bad     6

In [249]:
df2["cats"] = df2["cats"].astype("category")

In [251]:
df2["cats"].cat.set_categories(["very bad","bad","medium","good","very good"],inplace=True)

In [253]:
df2.dtypes

Unnamed: 0       int64
cats          category
vals             int64
dtype: object

In [254]:
df2['cats']

0    very good
1         good
2         good
3    very good
4    very good
5          bad
Name: cats, dtype: category
Categories (5, object): [very bad, bad, medium, good, very good]