In [1]:
import numpy as np
import pandas as pd


In [3]:
data = pd.DataFrame({'Country':['Russia','Colombia','Chile','Equador','Nigeria'],'Rank':[121,40,100,130,11]})

In [4]:
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [5]:
data = pd.DataFrame({'group':['a','a','a','b','b','b','c','c','c'],'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [6]:
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [7]:
data.sort_values(by=['ounces'],ascending = True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [8]:
data.sort_values(by=['group','ounces'],ascending = [False,False],inplace = False)

group  ounces
8     c     6.0
7     c     5.0
6     c     3.0
5     b     8.0
4     b     7.5
3     b     6.0
2     a    12.0
0     a     4.0
1     a     3.0

In [9]:
data = pd.DataFrame({'k1':['one']*3 + ['two']*4,'k2':[3,2,1,3,3,4,4]})

In [10]:
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [11]:
data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [12]:
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [13]:
data.drop_duplicates(subset = 'k1')

k1  k2
0  one   3
3  two   3

In [14]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','pastrami','corned beef','bacon','pastrami','honey ham','nova lox'],'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [16]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [21]:
def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'
    
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [23]:
lower = lambda x : x.lower()
data['food'] = data['food'].apply(lower)

In [26]:
data['animal2'] = data.apply(meat_2_animal,axis='columns')

In [27]:
data

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

In [2]:
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})

In [4]:
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [5]:
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [6]:
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [12]:
data = pd.DataFrame({'k1':['one']*3 + ['two']*4,'k2':[1,2,30,4,5,6,7]})

In [13]:
data

k1  k2
0  one   1
1  one   2
2  one  30
3  two   4
4  two   5
5  two   6
6  two   7

In [15]:
data.sort_values(by='k2')

k1  k2
0  one   1
1  one   2
3  two   4
4  two   5
5  two   6
6  two   7
2  one  30

In [16]:
data.drop_duplicates()

k1  k2
0  one   1
1  one   2
2  one  30
3  two   4
4  two   5
5  two   6
6  two   7

In [17]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   1
3  two   4

In [18]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [19]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'


In [20]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [21]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [23]:
lower = lambda x : x.lower()
data['food'] = data['food'].apply(lower)
data['animal2'] = data.apply(meat_2_animal,axis=1)

In [24]:
data

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

In [27]:
data.assign(new_variable = data['ounces']*10)

food  ounces  animal animal2 animal3  new_variable
0        bacon     4.0     pig     pig     pig          40.0
1  pulled pork     3.0     pig     pig     pig          30.0
2        bacon    12.0     pig     pig     pig         120.0
3     pastrami     6.0     cow     cow     cow          60.0
4  corned beef     7.5     cow     cow     cow          75.0
5        bacon     8.0     pig     pig     pig          80.0
6     pastrami     3.0     cow     cow     cow          30.0
7    honey ham     5.0     pig     pig     pig          50.0
8     nova lox     6.0  salmon  salmon  salmon          60.0

In [28]:
data.drop('animal2',axis='columns',inplace=True)

In [29]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [30]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [31]:
data.replace(-999,np.nan,inplace=True)

In [32]:
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [33]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [34]:
data.replace([-999,-1000],np.nan,inplace = True)

In [35]:
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [36]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])


In [37]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [38]:
data.rename(index = {'Ohio':'SanF'},columns={'one':'one_p','two':'two_p'})

one_p  two_p  three  four
SanF          0      1      2     3
Colorado      4      5      6     7
New York      8      9     10    11

In [39]:
data.rename(index = str.upper,columns=str.title,inplace=True)

In [40]:
data

One  Two  Three  Four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [41]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [42]:
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)

In [43]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [44]:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [48]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [49]:
bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']


In [54]:
new_cats = pd.cut(ages,bins,labels = bin_names)

In [55]:
new_cats

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAge, MiddleAge, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAge < Senior]

In [57]:
[[pd.value_counts(new_cats)]]

[[Youth         5
  MiddleAge     3
  YoungAdult    3
  Senior        1
  dtype: int64]]

In [58]:
pd.value_counts(new_cats).cumsum()

Youth          5
MiddleAge      8
YoungAdult    11
Senior        12
dtype: int64

In [61]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  0.599489 -0.913169
1    a  two -1.151268  1.561708
2    b  one  1.534490  0.753949
3    b  two -1.766277 -1.011431
4    a  one  0.903440  1.768972

In [66]:
grouped = df['data1'].groupby(df['key1']).mean()

In [68]:
grouped #in this case we took key1 which has all the a values and took its mean later we took b and took its mean and this is the value we have in the below table

key1
a    0.117220
b   -0.115894
Name: data1, dtype: float64

In [69]:
dates = pd.date_range('20130101',periods=6)

In [71]:
dates = pd.date_range('20130101',periods=6)

In [72]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [73]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df


A         B         C         D
2013-01-01 -0.786526  0.564681  1.784442 -0.443603
2013-01-02 -0.796646 -0.129137  0.047055  0.133799
2013-01-03  1.522998 -0.393086  0.247919  0.232291
2013-01-04  1.553916  0.749421 -0.345427 -1.211036
2013-01-05 -0.332073 -0.018710  0.094659 -0.641817
2013-01-06 -0.102188 -0.694051  1.253015 -0.982457

In [74]:
df[:3]

A         B         C         D
2013-01-01 -0.786526  0.564681  1.784442 -0.443603
2013-01-02 -0.796646 -0.129137  0.047055  0.133799
2013-01-03  1.522998 -0.393086  0.247919  0.232291

In [75]:
df['20130101':'20130104']

A         B         C         D
2013-01-01 -0.786526  0.564681  1.784442 -0.443603
2013-01-02 -0.796646 -0.129137  0.047055  0.133799
2013-01-03  1.522998 -0.393086  0.247919  0.232291
2013-01-04  1.553916  0.749421 -0.345427 -1.211036

In [77]:
df.loc[:,['A','B']]

A         B
2013-01-01 -0.786526  0.564681
2013-01-02 -0.796646 -0.129137
2013-01-03  1.522998 -0.393086
2013-01-04  1.553916  0.749421
2013-01-05 -0.332073 -0.018710
2013-01-06 -0.102188 -0.694051

In [78]:
df.loc['20130102':'20130103',['A','B']]

A         B
2013-01-02 -0.796646 -0.129137
2013-01-03  1.522998 -0.393086

In [79]:
df.iloc[3]

A    1.553916
B    0.749421
C   -0.345427
D   -1.211036
Name: 2013-01-04 00:00:00, dtype: float64

In [80]:
df.iloc[2:4,0:2]

A         B
2013-01-03  1.522998 -0.393086
2013-01-04  1.553916  0.749421

In [81]:
df.iloc[[1,5],[0,2]]

A         C
2013-01-02 -0.796646  0.047055
2013-01-06 -0.102188  1.253015

In [82]:
df2 = df.copy()
df2['E'] = ['one', 'one','two','three','four','three']

In [83]:
df2

A         B         C         D      E
2013-01-01 -0.786526  0.564681  1.784442 -0.443603    one
2013-01-02 -0.796646 -0.129137  0.047055  0.133799    one
2013-01-03  1.522998 -0.393086  0.247919  0.232291    two
2013-01-04  1.553916  0.749421 -0.345427 -1.211036  three
2013-01-05 -0.332073 -0.018710  0.094659 -0.641817   four
2013-01-06 -0.102188 -0.694051  1.253015 -0.982457  three

In [84]:
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03  1.522998 -0.393086  0.247919  0.232291   two
2013-01-05 -0.332073 -0.018710  0.094659 -0.641817  four

In [85]:
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03  1.522998 -0.393086  0.247919  0.232291   two
2013-01-05 -0.332073 -0.018710  0.094659 -0.641817  four

In [86]:
#select all the rows except thosee with two and four
df2[~df2.isin(['two','four'])]

A         B         C         D      E
2013-01-01 -0.786526  0.564681  1.784442 -0.443603    one
2013-01-02 -0.796646 -0.129137  0.047055  0.133799    one
2013-01-03  1.522998 -0.393086  0.247919  0.232291    NaN
2013-01-04  1.553916  0.749421 -0.345427 -1.211036  three
2013-01-05 -0.332073 -0.018710  0.094659 -0.641817    NaN
2013-01-06 -0.102188 -0.694051  1.253015 -0.982457  three

In [88]:
df2[~df2['E'].isin(['two','four'])]

A         B         C         D      E
2013-01-01 -0.786526  0.564681  1.784442 -0.443603    one
2013-01-02 -0.796646 -0.129137  0.047055  0.133799    one
2013-01-04  1.553916  0.749421 -0.345427 -1.211036  three
2013-01-06 -0.102188 -0.694051  1.253015 -0.982457  three

In [89]:
 ['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [90]:
lambda x: x+1

<function __main__.<lambda>(x)>

In [97]:
val = np.arange(0,36,1)

In [98]:
val

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [101]:
matrix=val.reshape(6,6)

In [103]:
matrix[::7]

array([[0, 1, 2, 3, 4, 5]])

In [104]:
matrix[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [105]:
matrix[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [108]:
matrix.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [109]:
matrix[[2,3],[2,3]]

array([14, 21])

In [110]:
matrix[2:4,2:4]

array([[14, 15],
       [20, 21]])